### ISSUE TITLE
Migrate the ZkpKeys class from Nightfall to SDK

### ISSUE THREAD

**Issue by rael-b** [NightfallRollup/nightfall-sdk#13]
The migration of the class [ZkpKeys](https://github.com/NightfallRollup/nightfall_3.5/blob/master/nightfall-client/src/services/keys.mjs) from _Nightfall_ to _Nightfall SDK_ is necessary, since the platform is going to heavily use it in order to generate the accounts for the actors and other additional things.

**Comment by imagobea** [comment]
Closing this one for now since there's already a util that allows ZK keys creation. This is via Client (far from ideal), but bringing class from Nightfall into SDK will require some work - not priority.

**Comment by rael-b** [comment]
Hello @imagobea, this task shouldn't be closed, but be kept in the TODO list, since it is a desirable feature.
