### ISSUE TITLE
Clarify transaction scripts

### ISSUE THREAD

**Issue by druiz0992** [NightfallRollup/nightfall-sdk#5]
There is some confusion with SDK transaction scripts

Specifically, why do we need this?

```   
 userSender = await UserFactory.create({
      clientApiUrl: config.clientApiUrl,
      ethereumPrivateKey: config.ethereumPrivateKey,
      nightfallMnemonic: config.nightfallMnemonic,
      blockchainWsUrl: config.blockchainWsUrl,
    });
```
Most of the confusion is due to the need of adding the `ethereumPrivateKey`.

**Comment by imagobea** [comment]
TODO

- [x] Util plus script to generate L2 keys
- [x] Document script above
- [x] Comment on `transfer` script
- [x] Explain `UserFactory` in README plus document factory
- [x] Make sure that utils are available from NPM package
