### ISSUE TITLE
Proof of transaction

### ISSUE THREAD

**Issue by druiz0992** [NightfallRollup/nightfall-sdk#6]
The user submits a request to the proposer to send a proof of transaction. This proof could be simply the L2 transaction hash. 

The hash only shows that a given transaction has happened, but it doesnt give any information on who the source, destination or asset is, so the hash may not be enough.

**Comment by imagobea** [comment]
In preparation for sdk part II of this issue, please see https://github.com/EYBlockchain/nightfall_3/pull/1366
